module.exports = [
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/components/SwipeFeed.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/components/SwipeFeed.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/SwipeFeed.tsx <module evaluation>", "default");
}),
"[project]/components/SwipeFeed.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/components/SwipeFeed.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/SwipeFeed.tsx", "default");
}),
"[project]/components/SwipeFeed.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$SwipeFeed$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/components/SwipeFeed.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$SwipeFeed$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/components/SwipeFeed.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$SwipeFeed$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/utils/ad-rotation.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "shuffleAdsForDate",
    ()=>shuffleAdsForDate
]);
function hashString(value) {
    let hash = 2166136261;
    for(let index = 0; index < value.length; index++){
        hash ^= value.charCodeAt(index);
        hash = Math.imul(hash, 16777619);
    }
    return hash >>> 0;
}
function shuffleAdsForDate(ads, dateKey) {
    return [
        ...ads
    ].sort((left, right)=>{
        const leftHash = hashString(`${dateKey}:${left.id}`);
        const rightHash = hashString(`${dateKey}:${right.id}`);
        if (leftHash !== rightHash) {
            return leftHash - rightHash;
        }
        return left.id.localeCompare(right.id);
    });
}
}),
"[project]/utils/ads.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "fetchActiveAds",
    ()=>fetchActiveAds
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/utils/supabase/server.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$ad$2d$rotation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/utils/ad-rotation.ts [app-rsc] (ecmascript)");
;
;
async function fetchActiveAds() {
    const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
    const today = new Date().toISOString().slice(0, 10);
    const { data } = await supabase.from("ads").select("id, image_url, company_name, click_url").eq("is_active", true).lte("start_date", today).gte("end_date", today).order("company_name", {
        ascending: true
    });
    const ads = (data ?? []).map((row)=>({
            id: row.id,
            imageUrl: row.image_url,
            companyName: row.company_name,
            clickUrl: row.click_url
        }));
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$ad$2d$rotation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["shuffleAdsForDate"])(ads, today);
}
}),
"[project]/app/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>HomePage,
    "dynamic",
    ()=>dynamic
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/utils/supabase/server.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$adopter$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/utils/adopter.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$supabase$2f$admin$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/utils/supabase/admin.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$SwipeFeed$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/SwipeFeed.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$ads$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/utils/ads.ts [app-rsc] (ecmascript)");
;
;
;
;
;
;
const dynamic = "force-dynamic";
function hasUploadedPhoto(dog) {
    return dog.photos.some((photo)=>{
        if (!photo.public_url) return false;
        try {
            const hostname = new URL(photo.public_url).hostname;
            return hostname.includes("backblazeb2.com") || hostname.includes("supabase.co");
        } catch  {
            return false;
        }
    });
}
async function getDogs() {
    const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
    const { data: dogs } = await supabase.from("dogs").select("*").eq("adoption_status", "available").order("created_at", {
        ascending: false
    });
    if (!dogs || dogs.length === 0) return [];
    const ids = dogs.map((d)=>d.id);
    const { data: photos } = await supabase.from("dog_photos").select("dog_id, public_url, is_cover, sort_order").in("dog_id", ids).order("sort_order");
    const { data: traits } = await supabase.from("dog_traits").select("dog_id, trait_type, trait_value").in("dog_id", ids).order("created_at");
    const photoMap = new Map();
    for (const p of photos ?? []){
        if (!photoMap.has(p.dog_id)) photoMap.set(p.dog_id, []);
        photoMap.get(p.dog_id).push(p);
    }
    const traitMap = new Map();
    for (const trait of traits ?? []){
        if (!traitMap.has(trait.dog_id)) traitMap.set(trait.dog_id, []);
        traitMap.get(trait.dog_id).push({
            trait_type: trait.trait_type,
            trait_value: trait.trait_value
        });
    }
    const videoMap = new Map();
    for (const [dogId, dogTraits] of traitMap){
        const publicUrl = dogTraits.find((trait)=>trait.trait_type === "cover_video_url")?.trait_value;
        if (!publicUrl) continue;
        videoMap.set(dogId, {
            public_url: publicUrl,
            poster_url: dogTraits.find((trait)=>trait.trait_type === "cover_video_poster_url")?.trait_value ?? null
        });
    }
    return dogs.map((d)=>({
            ...d,
            photos: photoMap.get(d.id) ?? [],
            traits: traitMap.get(d.id) ?? [],
            video: videoMap.get(d.id) ?? null
        })).sort((a, b)=>{
        const aUploaded = hasUploadedPhoto(a);
        const bUploaded = hasUploadedPhoto(b);
        if (aUploaded !== bUploaded) return aUploaded ? -1 : 1;
        return new Date(b.created_at).getTime() - new Date(a.created_at).getTime();
    });
}
async function HomePage() {
    const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClient"])();
    const { data: { user } } = await supabase.auth.getUser();
    const [dogs, ads] = await Promise.all([
        getDogs(),
        (0, __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$ads$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["fetchActiveAds"])()
    ]);
    let savedIds = [];
    if (user) {
        const adopter = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$adopter$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ensureAdopterForUser"])(supabase, user);
        const admin = (0, __TURBOPACK__imported__module__$5b$project$5d2f$utils$2f$supabase$2f$admin$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createAdminClient"])();
        const { data: wishlist } = await admin.from("wishlists").select("dog_id").eq("adopter_id", adopter.id);
        savedIds = (wishlist ?? []).map((w)=>w.dog_id);
    }
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$SwipeFeed$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
        dogs: dogs,
        savedIds: savedIds,
        isLoggedIn: !!user,
        ads: ads
    }, void 0, false, {
        fileName: "[project]/app/page.tsx",
        lineNumber: 100,
        columnNumber: 10
    }, this);
}
}),
"[project]/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__10cyb5r._.js.map